### 1.Importation des bibliothèques et chargement des données

In [ ]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/Users/madina/Analyse des produits Flipkart/data/Flipkart Dataset.csv")

### 2.Exploration initiale du dataset

In [4]:
data.head()

,product name,price,rating,number of buyers,total sold,available stock,main category,sub category,discount,seller,return policy,product url
0,Krishnamurthy-Devan Laboriosam Ultra Smartphon...,142247.04,3.2,7348,4812,364,Electronics,Smartphones,45,RetailNet,False,https://www.flipkart.com/Krishnamurthy-Devan-L...
1,Nanda-Mahal Dignissimos Lite Laptops 1,186922.43,4.1,2342,881,145,Electronics,Laptops,55,Flipkart Assured,False,https://www.flipkart.com/Nanda-Mahal-Dignissim...
2,Choudhury LLC Amet Plus Decor 15,11843.41,5.0,739,2580,206,Home,Decor,58,SuperComNet,True,https://www.flipkart.com/Choudhury-LLC-Amet-Pl...
3,Borah LLC Accusantium Lite Smartphones 9,10864.31,4.8,1543,4562,1585,Electronics,Smartphones,0,ElectroWorld,False,https://www.flipkart.com/Borah-LLC-Accusantium...
4,Murty Inc Placeat Pro Smartwatches 8,32950.41,4.5,7702,4925,1064,Electronics,Smartwatches,18,MobileHub,False,https://www.flipkart.com/Murty-Inc-Placeat-Pro...

In [5]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [6]:
data.shape

(5000, 12)

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product name      5000 non-null   str
 1   price             5000 non-null   float64
 2   rating            5000 non-null   float64
 3   number of buyers  5000 non-null   int64
 4   total sold        5000 non-null   int64
 5   available stock   5000 non-null   int64
 6   main category     5000 non-null   str
 7   sub category      5000 non-null   str
 8   discount          5000 non-null   int64
 9   seller            5000 non-null   str
 10  return policy     5000 non-null   bool
 11  product url       5000 non-null   str
dtypes: bool(1), float64(2), int64(4), str(5)
memory usage: 434.7 KB

In [8]:
data.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product name,5000,5000,Krishnamurthy-Devan Laboriosam Ultra Smartphon...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,5000.0,NaN,NaN,NaN,35884.09435,39867.681428,100.45,12275.5025,27761.01,42852.2475,249158.91
rating,5000.0,NaN,NaN,NaN,4.00364,0.584742,3.0,3.5,4.0,4.5,5.0
number of buyers,5000.0,NaN,NaN,NaN,5044.4256,2886.016013,11.0,2553.75,5099.5,7575.5,10000.0
total sold,5000.0,NaN,NaN,NaN,5005.0662,2897.042048,50.0,2495.0,4972.5,7571.5,10000.0
available stock,5000.0,NaN,NaN,NaN,1250.8702,1109.872427,0.0,323.75,916.0,1934.25,4924.0
main category,5000,4,Electronics,1275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sub category,5000,16,Refrigerators,352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount,5000.0,NaN,NaN,NaN,26.208,23.484332,0.0,0.0,23.0,47.0,70.0
seller,5000,8,RetailNet,661,NaN,NaN,NaN,NaN,NaN,NaN,NaN
return policy,5000,2,True,2564,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product url,5000,5000,https://www.flipkart.com/Krishnamurthy-Devan-L...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data.columns.tolist()

['product name',
 'price',
 'rating',
 'number of buyers',
 'total sold',
 'available stock',
 'main category',
 'sub category',
 'discount',
 'seller',
 'return policy',
 'product url']

### 3.Évaluation de la qualité des données

In [10]:
data.isnull().sum()

product name        0
price               0
rating              0
number of buyers    0
total sold          0
available stock     0
main category       0
sub category        0
discount            0
seller              0
return policy       0
product url         0
dtype: int64

In [11]:
data.duplicated().sum()

np.int64(0)

### 4.Nettoyage et normalisation des noms de colonnes

In [12]:
data.columns = (
    data.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

### 5. Nettoyage des variables catégorielles

In [13]:
text_columns = [
    "product_name",
    "main_category",
    "sub_category",
    "seller",
    "return_policy"
]

In [14]:
# supprimer les espaces inutiles
for col in text_columns:
    data[col] = data[col].astype("string").str.strip()

In [15]:
data["main_category"].value_counts(dropna=False)

main_category
Electronics    1275
Appliances     1263
Fashion        1239
Home           1223
Name: count, dtype: Int64

In [16]:
data["sub_category"].value_counts(dropna=False)

sub_category
Refrigerators       352
Laptops             343
Kitchenware         325
T-Shirts            320
Shoes               317
Headphones          316
Washing Machines    311
Smartphones         308
Smartwatches        308
Dresses             308
Decor               306
Lighting            305
ACs                 303
Microwaves          297
Jeans               294
Furniture           287
Name: count, dtype: Int64

In [17]:
data["return_policy"].value_counts(dropna=False)

return_policy
True     2564
False    2436
Name: count, dtype: Int64

### 6. Analyse et validation des variables numériques

In [18]:
numeric_columns = [
    "price",
    "rating",
    "number_of_buyers",
    "total_sold",
    "available_stock",
    "discount"
]

In [19]:
data[numeric_columns].dtypes

price               float64
rating              float64
number_of_buyers      int64
total_sold            int64
available_stock       int64
discount              int64
dtype: object

In [20]:
data[
    (data["rating"] < 0) |
    (data["rating"] > 5)
]

Empty DataFrame
Columns: [product_name, price, rating, number_of_buyers, total_sold, available_stock, main_category, sub_category, discount, seller, return_policy, product_url]
Index: []

In [21]:
data[
    (data["discount"] < 0) |
    (data["discount"] > 100)
]

Empty DataFrame
Columns: [product_name, price, rating, number_of_buyers, total_sold, available_stock, main_category, sub_category, discount, seller, return_policy, product_url]
Index: []

In [22]:
data[data["price"] <= 0]

Empty DataFrame
Columns: [product_name, price, rating, number_of_buyers, total_sold, available_stock, main_category, sub_category, discount, seller, return_policy, product_url]
Index: []

In [23]:
data[
    ~data["product_url"].astype("string").str.startswith(
        ("http://", "https://"),
        na=False
    )
]

Empty DataFrame
Columns: [product_name, price, rating, number_of_buyers, total_sold, available_stock, main_category, sub_category, discount, seller, return_policy, product_url]
Index: []

### 7.Création des variables dérivées

In [24]:
data["estimated_revenue"] = (
    data["price"] * data["total_sold"]
)

In [25]:
data["sell_through_rate"] = (
    data["total_sold"] /
    (data["total_sold"] + data["available_stock"])
)

In [26]:
data["sell_through_rate"].describe()

count    5000.000000
mean        0.811268
std         0.095121
min         0.666667
25%         0.727117
50%         0.799938
75%         0.890476
max         1.000000
Name: sell_through_rate, dtype: float64

### 8.Classification du stock et des réductions

In [27]:
data["stock_status"] = np.select(
    [
        data["available_stock"] < 10,
        data["available_stock"].between(10, 50)
    ],
    [
        "Low Stock",
        "Medium Stock"
    ],
    default="High Stock"
)

In [28]:
data["discount_band"] = pd.cut(
    data["discount"],
    bins=[-1, 10, 20, 30, 40, 100],
    labels=[
        "0-10%",
        "10-20%",
        "20-30%",
        "30-40%",
        "40%+"
    ]
)

In [29]:
data.head()

,product_name,price,rating,number_of_buyers,total_sold,available_stock,main_category,sub_category,discount,seller,return_policy,product_url,estimated_revenue,sell_through_rate,stock_status,discount_band
0,Krishnamurthy-Devan Laboriosam Ultra Smartphon...,142247.04,3.2,7348,4812,364,Electronics,Smartphones,45,RetailNet,False,https://www.flipkart.com/Krishnamurthy-Devan-L...,6.844928e+08,0.929675,High Stock,40%+
1,Nanda-Mahal Dignissimos Lite Laptops 1,186922.43,4.1,2342,881,145,Electronics,Laptops,55,Flipkart Assured,False,https://www.flipkart.com/Nanda-Mahal-Dignissim...,1.646787e+08,0.858674,High Stock,40%+
2,Choudhury LLC Amet Plus Decor 15,11843.41,5.0,739,2580,206,Home,Decor,58,SuperComNet,True,https://www.flipkart.com/Choudhury-LLC-Amet-Pl...,3.055600e+07,0.926059,High Stock,40%+
3,Borah LLC Accusantium Lite Smartphones 9,10864.31,4.8,1543,4562,1585,Electronics,Smartphones,0,ElectroWorld,False,https://www.flipkart.com/Borah-LLC-Accusantium...,4.956298e+07,0.742151,High Stock,0-10%
4,Murty Inc Placeat Pro Smartwatches 8,32950.41,4.5,7702,4925,1064,Electronics,Smartwatches,18,MobileHub,False,https://www.flipkart.com/Murty-Inc-Placeat-Pro...,1.622808e+08,0.822341,High Stock,10-20%

### 9. Export du dataset nettoyé

In [31]:
data.to_csv(
    "/Users/madina/Analyse des produits Flipkart/data/Cleaned_Flipkartdataset.csv",
    index=False
)